### ISSUE TITLE
Don't work currectly if i have difrent locales file

### ISSUE THREAD

**Issue by ghost** [michaelforney/dmenu#5]
If i have English system language and Danish keyboard layout dmenu don't work after first reboot?

**Comment by michaelforney** [comment]
Can you provide more details? Are you using the wayland branch of dmenu? Which compositor? What do you mean by "dmenu don't work"?

I use dmenu with en_US.UTF-8 and the Dvorak keyboard layout with no issues.

**Comment by ghost** [comment]
I3 with Xorg in Arch Linux

**Comment by michaelforney** [comment]
This repository is for the wayland port of dmenu. Since you are using Xorg, perhaps you meant to report a bug to the suckless mailing list?

See https://tools.suckless.org/dmenu/
